# Generated by Django 4.1.5 on 2023-01-24 13:11

import client.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='client',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_note',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='emarketing_solution',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Enterprise'), (3, 'No License')], default=3),
        ),
        migrations.AddField(
            model_name='client',
            name='events_solution',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Enterprise'), (3, 'No License')], default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=client.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='client',
            name='rfps_solution',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Enterprise'), (3, 'No License')], default=3),
        ),
        migrations.AddField(
            model_name='client',
            name='suppliers_solution',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Enterprise'), (3, 'No License')], default=3),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
