# Generated by Django 4.1 on 2022-08-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0001_initial'),
        ('sweet_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='sweet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet_shared.sweettype', verbose_name=''),
        ),
    ]
